### ISSUE TITLE
Bug: Cannot execute `monitor ls` command

### ISSUE THREAD

**Issue by mh166** [Zerka30/KumaCompanion#46]
## Describe the bug
When running the `monitor ls` command, it fails with an error.

### Steps to reproduce
- Build docker image
- Create `.env` file
- Run the command: `docker run --env-file .env --rm -it --network=host mh166/kumacompanion:git-74e8470 monitor ls`
- Get the following error message:
```
# docker run --env-file .env --rm -it --network=host mh166/kumacompanion:git-74e8470 monitor ls
Traceback (most recent call last):
  File "/app/src/main.py", line 44, in <module>
    main()
  File "/app/src/main.py", line 38, in main
    args.func(args)
  File "/app/src/commands/monitor/ls.py", line 125, in ls_monitors
    data_row.append(value[type])
                    ~~~~~^^^^^^
KeyError: 'group'
```

### Expected behavior
It should return a list of monitors available.

### Environment
```
# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy
# docker --version
Docker version 24.0.7, build afdd53b
# git rev-parse --short HEAD
74e8470
```

### Additional context
N/A. Please let me know if you need any other information.

**Comment by Zerka30** [comment]
Hi @mh166  👋 ,

Thanks you for reporting this bug.

We are currently investigating the reason for this bug. 
For the moment, I suspect it's the appearance and use of groups in uptime kuma, which is a relatively new feature. 

If necessary, we'll modify the implementation to take this use case into consideration.

**Comment by mh166** [comment]
Hi @Zerka30 👋 

Oh, so this feature was not there when you started implementing this companion? That would make a lot of sense then. Because, indeed, I am using several groups to ... well ... group the services 😅 according to their function and/or geographic location.

But with me being a relatively new user of Uptime Kuma, I was not aware of the fact that this (seemingly) basic feature has not always been available.

Thank you for looking into this matter. It is very much appreciated! Feel free to tell me if additional information is required. 😊

**Comment by Zerka30** [comment]
Yes, it's a feature that appeared in one of the last major Uptime Kuma updates.

We've carried out 2-3 tests, and have confirmed that this is indeed the problem. @leodbrs  will correct this shortly. 

Thanks for the feedback!

**Comment by Zerka30** [comment]
We keep this issue open, has we only have made a quick fix.

**Comment by rinchen** [comment]
To add some fuel.  I'm running this from a terminal. 

```
Traceback (most recent call last):
  File "./main.py", line 3, in <module>
    from commands.monitor import monitor
  File "/opt/KumaCompanion/src/commands/monitor/monitor.py", line 1, in <module>
    from . import add, ls, delete, pause, resume, edit, get
  File "/opt/KumaCompanion/src/commands/monitor/add.py", line 96
    match arg_name:
                 ^
SyntaxError: invalid syntax
```

**Comment by Zerka30** [comment]
Hi @rinchen :wave: 

Could you give the command your enter ?

**Comment by rinchen** [comment]
> Hi @rinchen 👋
> 
> Could you give the command your enter ?

Good point. I'm not using docker but calling main.py directly.

`python ./main.py monitor ls`

However, it doesn't matter what I put in there for args, it will always error exactly the same.
